export const FETCH_THEATER_STARTED = 'THEATER/FEITCH_STARTED';
export const FETCH_THEATER_SUCCESS = 'THEATER/FETCH_SUCCESS';
export const FETCH_THEATER_ERROR = 'THEATER/FETCH_ERROR';
export const FETCH_COMING_STARTED = 'COMING/FEITCH_STARTED';
export const FETCH_COMING_SUCCESS = 'COMING/FETCH_SUCCESS';
export const FETCH_COMING_ERROR = 'COMING/FETCH_ERROR';
